### ISSUE TITLE
[US] User Story Template Test

### ISSUE THREAD

**Issue by bluepuma38** [bluepuma38/Mentor#4]
**User Story:** As a [X], I need [Y] so that I can [Z].

**Acceptance Criteria:** 
* X
* Y
* Z

**Tasks:** 
1. X
2. Y
3. Z

**Definition of Done**
- [ ] Documentation and Artifacts Attached
- [ ] New Unit Tests Written & All Passing
- [ ] Test Plans Updated
- [ ] Test Automation Updated
- [ ] Demonstrated in Sprint Review
- [ ] Accepted by Product Owner
