### ISSUE TITLE
[US] Create & Style New Login Page

### ISSUE THREAD

**Issue by bluepuma38** [bluepuma38/Mentor#5]
**User Story:** As a Customer, I need a login page so that I can securely enter the website.

**Acceptance Criteria:** 
* New webpage added to project called LoginPage
* Includes two entry textboxes: Username and Password.
* Login button that passes the entered data to the backend API
* Styled based on project guidelines
* does **NOT** need to retrieve/process data back from the API at this point.

**Tasks**
- [x] Create new LoginPage class in project - 2h
- [x] Add text entry boxes and button - 3h
- [ ] Hook button to API - 1h
- [ ] Stylize Page - 4h
- [ ] Test Automation Updated - 2h
- [ ] Demonstrated in Sprint Review - 2h
- [ ] Accepted by Product Owner - 2h

**Definition of Done**
- [x] Documentation and Artifacts Attached
- [x] New Unit Tests Written & All Passing
- [ ] Code Reviewed by at least 2 Peers
- [ ] Test Plans Updated
- [ ] Test Automation Updated
- [ ] Demonstrated in Sprint Review
- [ ] Accepted by Product Owner
